CREATE DATABASE moviesite
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE USER 'moviesite'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES,
  LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER ON moviesite.* TO 'moviesite'@'localhost';